name: Grading

on:
  pull_request:
    branches: [ main ]

jobs:
  grading-test:
    runs-on: ubuntu-latest
    container: vladimirkutuev/cmocka:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2      
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Check repository clean
        run: ./2022-test-grading-tests/script/check_clean.sh
      - name: Test with memcheck
        run: ./2022-test-grading-tests/script/test.sh


